# Generated by Django 5.2.6 on 2025-09-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_category_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='organizer',
            new_name='created_by',
        ),
    ]
